#!/bin/sh
#-------------------------------------------------------------------------------
#
# This is a small Ubuntu script for installing MXE for use in cross-compiling
# DSView and/or sigrok and their dependencies for MinGW-w64/Windows systems
# using the i686-w64-mingw32.static.posix target mode.
#
# Status
# ------
#
# Working
#
#
# Requirements
# ------------
#
#  - bash
#  - gcc
#  - make
#  - cmake
#  - git
#  - wget
#  - p7zip
#  - pkg-config (>= 0.22)
#  - sdcc (needed for building the fx2lafw firmware)
#  - nsis
#  - MXE (*-w64-* targets, the *-pc-* targets are not supported)
#
#
# MXE setup
# ---------
#
# First, remove the exisating MXE package, if any
# $ cd into <path>/DSView/MXE (where this file is)
# $ ./build-mxe

sudo apt-get --purge autoremove mxe
rm -rf ~/mxe-git

# Then, get the MXE cross-compile environment for MinGW-w64/Windows:

git clone https://github.com/mxe/mxe.git ~/mxe-git
cp mxe_fixes.patch ~/mxe-git
cd ~/mxe-git

# Apply some fixes that are currently required for a proper build:

patch -p1 < mxe_fixes.patch

# Build all required packages:

echo This will take a while
make MXE_TARGETS=i686-w64-mingw32.static.posix \
    MXE_PLUGIN_DIRS=plugins/examples/qt5-freeze fftw \
    gcc glib libzip libusb1 libftdi1 glibmm qtbase qtimageformats qtsvg \
    boost check qtbase_CONFIGURE_OPTS='-no-sql-mysql'
echo done

#
# See http://mxe.cc for details on MXE.
#
# Note: We're "freezing" the Qt5 version to Qt 5.7.x, since that's the last
# version that supports Windows XP (which we currently still want to support).
#
#
# Building
# --------
#
# $ ./sigrok-cross-mingw
#
# Per default it expects MXE in:
#
# $HOME/mxe-git
#
# Per default it will install the cross-compiled packages in:
#
# $HOME/sr_mingw
#
# Please edit the script if you want to change any settings.

